In [1]:
import numpy as np

### Cread 3 arrays de una, dos y tres dimensiones.

In [2]:
lista1 = [2, 3, 7, 11, 23]

In [3]:
array_uni = np.array(lista1)
array_uni

array([ 2,  3,  7, 11, 23])

In [4]:
lista2 = [8, 11, 24, 83, 112]

In [5]:
array_bidi = np.array([lista1,lista2])
array_bidi

array([[  2,   3,   7,  11,  23],
       [  8,  11,  24,  83, 112]])

In [6]:
lista3 = [[3 ,4], [8, 12]]
lista4 = [[5, 6], [18, 29]]

In [7]:
array_tridi = np.array([lista3,lista4])
array_tridi

array([[[ 3,  4],
        [ 8, 12]],

       [[ 5,  6],
        [18, 29]]])

___________

### Cread una función que chequee las propiedades básicas de cada array que os hayáis creado.

In [8]:
def informar_arrays(array_a_comprobar):
    array_a_comprobar.shape
    array_a_comprobar.size
    array_a_comprobar.dtype
    array_a_comprobar.ndim
    return print(f"La forma de nuestra array es {array_a_comprobar.shape}. El tamaño de nuestra array es de {array_a_comprobar.size}. El tipo de nuestra array es {array_a_comprobar.dtype}. Y la dimensión de nuestra array es {array_a_comprobar.ndim}.")

In [9]:
informar_arrays(array_uni)

La forma de nuestra array es (5,). El tamaño de nuestra array es de 5. El tipo de nuestra array es int32. Y la dimensión de nuestra array es 1.


In [10]:
informar_arrays(array_bidi)

La forma de nuestra array es (2, 5). El tamaño de nuestra array es de 10. El tipo de nuestra array es int32. Y la dimensión de nuestra array es 2.


In [11]:
informar_arrays(array_tridi)

La forma de nuestra array es (2, 2, 2). El tamaño de nuestra array es de 8. El tipo de nuestra array es int32. Y la dimensión de nuestra array es 3.


__________

### Cread una matriz identidad de dos dimensiones de 3 filas y 3 columna.

In [12]:
ejercicio3 = np.identity(3)
ejercicio3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

_____________

### Cread una matriz de tres dimensiones de unos igual a la martiz de tres dimensiones creada en el primer ejercicio.

In [13]:
ejercicio4 = np.ones_like(array_tridi)
ejercicio4

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

_________________

### Operaciones entre arrays.

### ¿Se puede sumar el array de dos dimensiones que creamos en el primer ejecicios a la matriz identidad? ¿Por qué?

No se pueden hacer este tipo de operaciones porque las dos arrays tienen diferentes forma.

### En caso de que no se puedan sumar, busca una solución para sumar una matriz identidad a otra. 

In [ ]:
array_nueva = np.array([[2, 5, 4], [8, 9, 12], [10, 20, 30]])

In [ ]:
np.add(array_nueva, ejercicio3)

array([[ 3.,  5.,  4.],
       [ 8., 10., 12.],
       [10., 20., 31.]])

### Multiplicad la matriz identidad por la nueva matriz que os creasteis en el ejercicio anterior.

In [ ]:
np.multiply(array_nueva, ejercicio3)

array([[ 2.,  0.,  0.],
       [ 0.,  9.,  0.],
       [ 0.,  0., 30.]])

### Dividid las dos matrices

In [ ]:
np.divide(array_nueva, ejercicio3)

/var/folders/66/3gn2x5sj3tlfxjp4wp1zg9n00000gn/T/ipykernel_10360/1718934103.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.divide(array_nueva, ejercicio3)


array([[ 2., inf, inf],
       [inf,  9., inf],
       [inf, inf, 30.]])

Nos da el "error" por dividir por 0. No hacemos nada porque entendemos que el resultado es normal.