In [1]:
import numpy as np

### Cread un array de dos dimensiones de 5 filas y 3 columnas. 

### Sobre el array creado anteriormente, extraed:

In [2]:
array_1 = np.random.rand(5,3).round(2)
array_1

array([[0.66, 0.39, 0.35],
       [0.  , 0.89, 0.61],
       [0.9 , 0.57, 0.23],
       [0.5 , 0.75, 0.86],
       [0.01, 0.57, 0.55]])

### El valor de la primera fila y la segunda columna.

In [3]:
array_1[0,1]

0.39

### Los valores de la segunda fila y las dos primeras columnas.

In [4]:
array_1[1,:2]

array([0.  , 0.89])

### Extraed las filas pares (incluyendo la 0) y todas las columnas.

In [5]:
array_1[0::2,:]

array([[0.66, 0.39, 0.35],
       [0.9 , 0.57, 0.23],
       [0.01, 0.57, 0.55]])

### Extraed los valores que sean mayores que 0.5.

In [6]:
array_1[array_1>0.5]

array([0.66, 0.89, 0.61, 0.9 , 0.57, 0.75, 0.86, 0.57, 0.55])

### Extraed los valores menores que 0.2 o mayores que 0.5

In [7]:
array_1[(array_1<0.2) | (array_1>0.5)]

array([0.66, 0.  , 0.89, 0.61, 0.9 , 0.57, 0.75, 0.86, 0.01, 0.57, 0.55])

____________

### Cread dos array de tres dimensiones:

El primero de 2 matrices, 5 filas y 3 columnas.

In [8]:
array_2 = np.random.rand(2,5,3).round(2)
print(array_2)


[[[0.82 0.34 0.87]
  [0.96 0.57 0.57]
  [0.01 0.8  0.66]
  [0.75 0.05 0.65]
  [0.68 0.09 0.45]]

 [[0.29 0.03 0.62]
  [0.49 0.36 0.41]
  [0.05 0.08 0.2 ]
  [0.68 0.19 0.12]
  [0.32 0.41 0.01]]]


El segundo de 3 matrices, 2 filas y 5 columnas

In [9]:
array_3 = np.random.rand(3,2,5).round(2)
print(array_3)

[[[0.27 0.98 0.13 0.6  0.25]
  [0.76 0.24 0.09 0.92 0.08]]

 [[0.84 0.32 0.01 0.07 0.63]
  [0.33 0.7  0.31 0.1  0.18]]

 [[0.8  0.27 0.   0.59 0.73]
  [0.5  0.58 0.94 0.38 0.64]]]


________________

### Haced un análisis exploratorio de los array creados.

In [10]:
def informar_arrays(array_a_comprobar):
    array_a_comprobar.shape
    array_a_comprobar.size
    array_a_comprobar.dtype
    array_a_comprobar.ndim
    return print(f"La forma de nuestra array es {array_a_comprobar.shape}. El tamaño de nuestra array es de {array_a_comprobar.size}. El tipo de nuestra array es {array_a_comprobar.dtype}. Y la dimensión de nuestra array es {array_a_comprobar.ndim}.")

In [11]:
informar_arrays(array_2)

La forma de nuestra array es (2, 5, 3). El tamaño de nuestra array es de 30. El tipo de nuestra array es float64. Y la dimensión de nuestra array es 3.


In [12]:
informar_arrays(array_3)

La forma de nuestra array es (3, 2, 5). El tamaño de nuestra array es de 30. El tipo de nuestra array es float64. Y la dimensión de nuestra array es 3.


_____________

### Sumad los dos arrays. ¿Podéis? ¿Por qué?

In [13]:
np.add(array_2,array_3)

ValueError: operands could not be broadcast together with shapes (2,5,3) (3,2,5) 

No se puede sumar porque las dos *arrays* no tienen la misma *shape*/forma.

Para cambiar la forma de un array y poder hacer operaciones entre arrays que tienen distintas formas hemos aprendido dos métodos:
- reshape()
- transpose()

In [14]:
array_3_cambiada = np.transpose(array_3,(1,2,0))
array_3_cambiada

array([[[0.27, 0.84, 0.8 ],
        [0.98, 0.32, 0.27],
        [0.13, 0.01, 0.  ],
        [0.6 , 0.07, 0.59],
        [0.25, 0.63, 0.73]],

       [[0.76, 0.33, 0.5 ],
        [0.24, 0.7 , 0.58],
        [0.09, 0.31, 0.94],
        [0.92, 0.1 , 0.38],
        [0.08, 0.18, 0.64]]])

In [15]:
array_3_shape = np.reshape(array_3,(2,5,3))
array_3_shape

array([[[0.27, 0.98, 0.13],
        [0.6 , 0.25, 0.76],
        [0.24, 0.09, 0.92],
        [0.08, 0.84, 0.32],
        [0.01, 0.07, 0.63]],

       [[0.33, 0.7 , 0.31],
        [0.1 , 0.18, 0.8 ],
        [0.27, 0.  , 0.59],
        [0.73, 0.5 , 0.58],
        [0.94, 0.38, 0.64]]])

__________

### Una vez cambiada la forma de los array, haced operaciones entre ellos.

In [16]:
array_suma = np.add(array_2,array_3_cambiada)
array_suma

array([[[1.09, 1.18, 1.67],
        [1.94, 0.89, 0.84],
        [0.14, 0.81, 0.66],
        [1.35, 0.12, 1.24],
        [0.93, 0.72, 1.18]],

       [[1.05, 0.36, 1.12],
        [0.73, 1.06, 0.99],
        [0.14, 0.39, 1.14],
        [1.6 , 0.29, 0.5 ],
        [0.4 , 0.59, 0.65]]])

In [17]:
array_resta = np.subtract(array_2,array_3_shape)
array_resta

array([[[ 0.55, -0.64,  0.74],
        [ 0.36,  0.32, -0.19],
        [-0.23,  0.71, -0.26],
        [ 0.67, -0.79,  0.33],
        [ 0.67,  0.02, -0.18]],

       [[-0.04, -0.67,  0.31],
        [ 0.39,  0.18, -0.39],
        [-0.22,  0.08, -0.39],
        [-0.05, -0.31, -0.46],
        [-0.62,  0.03, -0.63]]])

In [18]:
array_multi = np.multiply(array_2, array_3_cambiada).round(2)
array_multi

array([[[0.22, 0.29, 0.7 ],
        [0.94, 0.18, 0.15],
        [0.  , 0.01, 0.  ],
        [0.45, 0.  , 0.38],
        [0.17, 0.06, 0.33]],

       [[0.22, 0.01, 0.31],
        [0.12, 0.25, 0.24],
        [0.  , 0.02, 0.19],
        [0.63, 0.02, 0.05],
        [0.03, 0.07, 0.01]]])

In [19]:
array_division = np.divide(array_2,array_3_shape).round(2)
array_division

/var/folders/66/3gn2x5sj3tlfxjp4wp1zg9n00000gn/T/ipykernel_10408/2579763873.py:1: RuntimeWarning: divide by zero encountered in true_divide
  array_division = np.divide(array_2,array_3_shape).round(2)


array([[[3.04e+00, 3.50e-01, 6.69e+00],
        [1.60e+00, 2.28e+00, 7.50e-01],
        [4.00e-02, 8.89e+00, 7.20e-01],
        [9.38e+00, 6.00e-02, 2.03e+00],
        [6.80e+01, 1.29e+00, 7.10e-01]],

       [[8.80e-01, 4.00e-02, 2.00e+00],
        [4.90e+00, 2.00e+00, 5.10e-01],
        [1.90e-01,      inf, 3.40e-01],
        [9.30e-01, 3.80e-01, 2.10e-01],
        [3.40e-01, 1.08e+00, 2.00e-02]]])