In [1]:
import numpy as np
import random

### ¿Cómo podemos crear dos arrays de dos dimensiones usando el método random_sample que tengan los mismos valores?

In [2]:
np.random.seed(42)
arr_1 = np.random.random_sample((2,5))
np.random.seed(42)
arr_2 = np.random.random_sample((2,5))

In [3]:
#Aqui podemos ver que los dos arrays son iguales
print(arr_1)
print(arr_2)

[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
 [0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]]
[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
 [0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]]


____________

### Cread los siguientes arrays:
    
- Un array de tres dimensiones con distribución uniforme de 2 x 3 x 5, con números entre 0 y 10, que no tengan decimales y extrae sus valores únicos almacenándolos en una variable.
- Un array de tres dimensiones con distribución binomial de 2 x 3 x 5, con probabilidad de 0.3 y número de pruebas igual a 10. Igual que antes, extrae sus valores únicos y guarda los datos en una variable.

In [4]:
arr_uniforme =np.round(np.random.uniform(0,10, size=(2,3,5)))
arr_uniforme

array([[[ 0., 10.,  8.,  2.,  2.],
        [ 2.,  3.,  5.,  4.,  3.],
        [ 6.,  1.,  3.,  4.,  5.]],

       [[ 8.,  2.,  5.,  6.,  0.],
        [ 6.,  2.,  1.,  9., 10.],
        [ 8.,  3.,  1.,  7.,  4.]]])

In [5]:
arr_bin = np.random.binomial(10, 0.3, size = (2,3,5))
arr_bin

array([[[1, 3, 1, 5, 2],
        [4, 2, 3, 3, 2],
        [6, 4, 5, 5, 3]],

       [[5, 1, 2, 1, 2],
        [3, 2, 4, 2, 2],
        [3, 1, 4, 1, 6]]])

__________

### Usando los arrays de elementos únicos obtenidos en el ejercicio anterior realizad las siguientes operaciones:

- Elementos comunes entre los dos arrays

In [6]:
arr_unique_1 = np.unique(arr_uniforme)
arr_unique_1

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [7]:
arr_unique_2 = np.unique(arr_bin)
arr_unique_2

array([1, 2, 3, 4, 5, 6])

In [8]:
arr_comunes = np.intersect1d(arr_unique_1,arr_unique_2)
arr_comunes

array([1., 2., 3., 4., 5., 6.])

 Hemos mirado los elementos unicos de los arrays con el metodo unique, porque como son de tres dimensiones así nos devolvia un array de una dimension.

 Asi podiamos usar el metodo intersect1d que solo admite una array de una dimension.

________________

-  Unión de los dos arrays

In [9]:
arr_union = np.union1d(arr_unique_1,arr_unique_2)
arr_union

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])


Siguiendo el exemplo de antes usamos el metodo union para unir los valores unicos de cada array.

- ¿Qué elementos están en el array derivado de la distribución uniforme y no en los únicos de la distribución binomial? Extrae los valores númericos

In [10]:
print(arr_unique_1)
print(arr_unique_2)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[1 2 3 4 5 6]


In [11]:
arr_diferencia = np.setdiff1d(arr_unique_1, arr_unique_2)
arr_diferencia

array([ 0.,  7.,  8.,  9., 10.])

Nos devuelve los elementos unicos que hay en la array_1 pero no hay en la array_2.

__________________

### Cread dos arrays usando el método random.randint de Numpy con 80 elementos cada uno con números del 1-100, con los siguientes nombres array1 y array2.

In [12]:
array1 = np.random.randint(1,100, 80)
array2 = np.random.randint(1,100, 80)

print(array1)
print(array2)

[88  1  8 88 63 11 81  8 35 35 33  5 41 28  7 73 72 12 34 33 48 23 62 88
 37 99 44 86 91 35 65 99 47 78  3  1  5 90 14 27  9 79 15 90 42 77 51 63
 96 52 96  4 94 23 15 43 29 36 13 32 71 59 86 28 66 42 45 62 57  6 28 28
 44 84 30 62 75 92 89 62]
[97  1 27 62 77  3 70 72 27  9 62 37 97 51 44 24 79 59 32 96 88 52 62 58
 52 12 39  2  3 56 81 59  2  2 92 54 87 96 97  1 19  2 53 44 90 32 70 32
 68 55 75 56 17 38 24 69 98 70 86 11 16 97 73 59 70 80 93  3 20 59 36 19
 90 67 19 20 96 71 52 33]


- Extraed los valores únicos de cada uno de los arrays y los guardáis en variables en las que se les llame array1 y array2.

In [13]:
array1 = np.unique(array1)
array2 = np.unique(array2)

print(array1)
print(array2)

[ 1  3  4  5  6  7  8  9 11 12 13 14 15 23 27 28 29 30 32 33 34 35 36 37
 41 42 43 44 45 47 48 51 52 57 59 62 63 65 66 71 72 73 75 77 78 79 81 84
 86 88 89 90 91 92 94 96 99]
[ 1  2  3  9 11 12 16 17 19 20 24 27 32 33 36 37 38 39 44 51 52 53 54 55
 56 58 59 62 67 68 69 70 71 72 73 75 77 79 80 81 86 87 88 90 92 93 96 97
 98]


- Identificad los elementos presentes en el array1 pero no en el array2 y asiganarlo a una variable que se llame array3.

In [14]:
array3 = np.setdiff1d(array1, array2)
array3

array([ 4,  5,  6,  7,  8, 13, 14, 15, 23, 28, 29, 30, 34, 35, 41, 42, 43,
       45, 47, 48, 57, 63, 65, 66, 78, 84, 89, 91, 94, 99])

- Identificad los elementos presentes en el array2 pero no en el array1 y asiganarlo a una variable que se llame array4.

In [15]:
array4 = np.setdiff1d(array2, array1)
array4

array([ 2, 16, 17, 19, 20, 24, 38, 39, 53, 54, 55, 56, 58, 67, 68, 69, 70,
       80, 87, 93, 97, 98])

- Identificad los elementos presentes en ambos arrays y asiganarlos a una variable que se llame array5.

In [16]:
array5 = np.intersect1d(array1,array2)
array5

array([ 1,  3,  9, 11, 12, 27, 32, 33, 36, 37, 44, 51, 52, 59, 62, 71, 72,
       73, 75, 77, 79, 81, 86, 88, 90, 92, 96])

- ¿Cuál es la relación que existe entre todos estos arrays?



In [17]:
print(len(array1))
print(len(array2))
print(len(array3))
print(len(array4))
print(len(array5))


57
49
30
22
27


In [18]:
(len(array1) + len(array2)) == len(array3)

False

In [19]:
len(array5) + (len(array4)) == len(array2)

True

Vemos que el len del array5 + el len del array 4 (27 + 22) dan como resultado el len del array2, 49

In [20]:
len(array5) + (len(array3)) == len(array1)

True

Vemos que el len del array5 + el len del array 4 (27 + 30) dan como resultado el len del array1, 57